version: '3'
services:
  db:
    container_name: "postgres-article"
    image: postgres:15.2
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    extends:
      file: postgres.yaml
      service: postgres
volumes:
  db:
    driver: local